apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress-path
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "cursok8s.localhost"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /hw1(/|$)(.*)
        backend:
          service:
            name: hello-kubernetes-first
            port:
              number: 8080
      - pathType: ImplementationSpecific
        path: /hw2(/|$)(.*)
        backend:
          service:
            name: hello-kubernetes-second
            port:
              number: 8080